-- Ejecutar completo en Supabase Dashboard > SQL Editor.
-- Crea perfiles, contenido de F1, datos iniciales, permisos y RLS.

create extension if not exists pgcrypto;

-- ============================================================
-- PERFILES (vinculados a Supabase Auth)
-- ============================================================
create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    first_name text not null default '',
    last_name text not null default '',
    avatar_url text,
    role text not null default 'user' check (role in ('user', 'admin')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
    insert into public.profiles (id, first_name, last_name)
    values (
        new.id,
        coalesce(new.raw_user_meta_data ->> 'first_name', ''),
        coalesce(new.raw_user_meta_data ->> 'last_name', '')
    )
    on conflict (id) do nothing;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert on auth.users
    for each row execute procedure public.handle_new_user();

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
    before update on public.profiles
    for each row execute procedure public.set_updated_at();

-- ============================================================
-- CONTENIDO
-- ============================================================
create table if not exists public.teams (
    id bigint generated by default as identity primary key,
    name text not null unique,
    short_name text not null,
    color_hex text not null default '#FFFFFF',
    logo_url text,
    created_at timestamptz not null default now()
);

create table if not exists public.drivers (
    id bigint generated by default as identity primary key,
    team_id bigint references public.teams(id) on delete set null,
    first_name text not null,
    last_name text not null,
    code text not null unique,
    driver_number integer not null unique,
    country text not null,
    birth_date date,
    photo_url text,
    championships integer not null default 0 check (championships >= 0),
    wins integer not null default 0 check (wins >= 0),
    podiums integer not null default 0 check (podiums >= 0),
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

drop trigger if exists drivers_set_updated_at on public.drivers;
create trigger drivers_set_updated_at
    before update on public.drivers
    for each row execute procedure public.set_updated_at();

create table if not exists public.seasons (
    year integer primary key check (year between 1950 and 2200),
    name text not null,
    active boolean not null default false
);

create table if not exists public.standings (
    id bigint generated by default as identity primary key,
    season_year integer not null references public.seasons(year) on delete cascade,
    driver_id bigint not null references public.drivers(id) on delete cascade,
    position integer not null check (position > 0),
    points numeric(8, 2) not null default 0 check (points >= 0),
    trend text not null default 'same' check (trend in ('up', 'down', 'same')),
    updated_at timestamptz not null default now(),
    unique (season_year, driver_id),
    unique (season_year, position)
);

create table if not exists public.races (
    id bigint generated by default as identity primary key,
    season_year integer not null references public.seasons(year) on delete cascade,
    round integer not null check (round > 0),
    name text not null,
    circuit_name text not null,
    country text not null,
    start_date date not null,
    end_date date not null,
    status text not null default 'scheduled'
        check (status in ('scheduled', 'live', 'finished', 'cancelled')),
    created_at timestamptz not null default now(),
    unique (season_year, round)
);

create table if not exists public.news (
    id bigint generated by default as identity primary key,
    title text not null,
    summary text,
    body text,
    image_url text,
    category text not null default 'F1',
    badge text,
    featured boolean not null default false,
    published boolean not null default true,
    published_at timestamptz not null default now(),
    author_id uuid references public.profiles(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

drop trigger if exists news_set_updated_at on public.news;
create trigger news_set_updated_at
    before update on public.news
    for each row execute procedure public.set_updated_at();

create index if not exists standings_season_position_idx
    on public.standings(season_year, position);
create index if not exists news_published_at_idx
    on public.news(published, published_at desc);
create index if not exists drivers_team_id_idx
    on public.drivers(team_id);

-- ============================================================
-- SEGURIDAD (ROW LEVEL SECURITY)
-- ============================================================
alter table public.profiles enable row level security;
alter table public.teams enable row level security;
alter table public.drivers enable row level security;
alter table public.seasons enable row level security;
alter table public.standings enable row level security;
alter table public.races enable row level security;
alter table public.news enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
    on public.profiles for select
    to authenticated
    using ((select auth.uid()) = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
    on public.profiles for update
    to authenticated
    using ((select auth.uid()) = id)
    with check ((select auth.uid()) = id);

drop policy if exists "teams_public_read" on public.teams;
create policy "teams_public_read"
    on public.teams for select to anon, authenticated using (true);

drop policy if exists "drivers_public_read" on public.drivers;
create policy "drivers_public_read"
    on public.drivers for select to anon, authenticated using (active = true);

drop policy if exists "seasons_public_read" on public.seasons;
create policy "seasons_public_read"
    on public.seasons for select to anon, authenticated using (true);

drop policy if exists "standings_public_read" on public.standings;
create policy "standings_public_read"
    on public.standings for select to anon, authenticated using (true);

drop policy if exists "races_public_read" on public.races;
create policy "races_public_read"
    on public.races for select to anon, authenticated using (true);

drop policy if exists "published_news_public_read" on public.news;
create policy "published_news_public_read"
    on public.news for select to anon, authenticated using (published = true);

-- Las escrituras de contenido se realizan desde Dashboard o servidor con service_role.
-- Nunca incluyas service_role en la aplicación Android.

grant usage on schema public to anon, authenticated;
grant select on public.teams, public.drivers, public.seasons,
    public.standings, public.races, public.news to anon, authenticated;
grant select, update on public.profiles to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- ============================================================
-- DATOS INICIALES
-- ============================================================
insert into public.seasons (year, name, active)
values (2026, 'Temporada 2026', true)
on conflict (year) do update set name = excluded.name, active = excluded.active;

insert into public.teams (name, short_name, color_hex) values
    ('Mercedes', 'MER', '#00D2BE'),
    ('Ferrari', 'FER', '#E8002D'),
    ('McLaren', 'MCL', '#FF8000'),
    ('Red Bull Racing', 'RBR', '#3671C6'),
    ('Williams', 'WIL', '#64C4FF'),
    ('Aston Martin', 'AMR', '#229971'),
    ('Alpine', 'ALP', '#FF87BC')
on conflict (name) do update
set short_name = excluded.short_name, color_hex = excluded.color_hex;

insert into public.drivers
    (team_id, first_name, last_name, code, driver_number, country,
     championships, wins, podiums)
values
    ((select id from public.teams where name='Mercedes'), 'Kimi', 'Antonelli', 'ANT', 12, 'Italia', 0, 0, 0),
    ((select id from public.teams where name='Ferrari'), 'Lewis', 'Hamilton', 'HAM', 44, 'Reino Unido', 7, 105, 202),
    ((select id from public.teams where name='Mercedes'), 'George', 'Russell', 'RUS', 63, 'Reino Unido', 0, 3, 15),
    ((select id from public.teams where name='Ferrari'), 'Charles', 'Leclerc', 'LEC', 16, 'Mónaco', 0, 8, 43),
    ((select id from public.teams where name='McLaren'), 'Lando', 'Norris', 'NOR', 4, 'Reino Unido', 0, 5, 30),
    ((select id from public.teams where name='Red Bull Racing'), 'Max', 'Verstappen', 'VER', 1, 'Países Bajos', 4, 62, 109),
    ((select id from public.teams where name='McLaren'), 'Oscar', 'Piastri', 'PIA', 81, 'Australia', 0, 4, 13),
    ((select id from public.teams where name='Williams'), 'Carlos', 'Sainz', 'SAI', 55, 'España', 0, 4, 27),
    ((select id from public.teams where name='Aston Martin'), 'Fernando', 'Alonso', 'ALO', 14, 'España', 2, 32, 106),
    ((select id from public.teams where name='Alpine'), 'Pierre', 'Gasly', 'GAS', 10, 'Francia', 0, 1, 5)
on conflict (code) do update set
    team_id = excluded.team_id,
    first_name = excluded.first_name,
    last_name = excluded.last_name,
    driver_number = excluded.driver_number,
    country = excluded.country,
    championships = excluded.championships,
    wins = excluded.wins,
    podiums = excluded.podiums;

insert into public.standings (season_year, driver_id, position, points, trend)
values
    (2026, (select id from public.drivers where code='ANT'), 1, 219, 'same'),
    (2026, (select id from public.drivers where code='HAM'), 2, 169, 'same'),
    (2026, (select id from public.drivers where code='RUS'), 3, 160, 'same'),
    (2026, (select id from public.drivers where code='LEC'), 4, 138, 'same'),
    (2026, (select id from public.drivers where code='NOR'), 5, 128, 'same'),
    (2026, (select id from public.drivers where code='VER'), 6, 109, 'up'),
    (2026, (select id from public.drivers where code='PIA'), 7, 92, 'down'),
    (2026, (select id from public.drivers where code='SAI'), 8, 74, 'same'),
    (2026, (select id from public.drivers where code='ALO'), 9, 58, 'up'),
    (2026, (select id from public.drivers where code='GAS'), 10, 41, 'down')
on conflict (season_year, driver_id) do update set
    position = excluded.position,
    points = excluded.points,
    trend = excluded.trend,
    updated_at = now();

insert into public.races
    (season_year, round, name, circuit_name, country, start_date, end_date, status)
values
    (2026, 13, 'Gran Premio de Argentina',
     'Autódromo Oscar y Juan Gálvez', 'Argentina',
     '2026-11-06', '2026-11-08', 'scheduled')
on conflict (season_year, round) do update set
    name = excluded.name,
    circuit_name = excluded.circuit_name,
    country = excluded.country,
    start_date = excluded.start_date,
    end_date = excluded.end_date,
    status = excluded.status;

insert into public.news (title, summary, category, badge, featured, published, image_url) values
    ('Autódromo Oscar y Juan Gálvez: la Catedral del Automovilismo argentino',
     'El histórico circuito porteño se prepara para una nueva etapa.', 'F1', 'UNLOCKED', true, true, 'news_featured'),
    ('Inaugurado en 1952, fue sede de 20 Grandes Premios de F1',
     'Historia del circuito argentino.', 'F1', 'UNLOCKED', false, true, 'news_galvez'),
    ('MotoGP vuelve a Buenos Aires en 2027, tras 28 años de ausencia',
     'La máxima categoría de motociclismo regresa a la ciudad.', 'MotoGP', null, false, true, 'news_motogp'),
    ('Remodelación de u$s100M para volver a estándares FIA',
     'El proyecto apunta a recibir competencias internacionales.', 'F1', null, false, true, 'news_featured'),
    ('190 hectáreas en Villa Riachuelo, Buenos Aires',
     'El predio combina historia, deporte y renovación urbana.', 'General', null, false, true, 'news_galvez');
